const imageGallery = [
  {
    id: 1,
    name: "Banda Laws Portfolio",
    desc: "A visually striking UI design concept that enhances user experience.",
    img: "https://firebasestorage.googleapis.com/v0/b/crudstudio-6fb0f.appspot.com/o/images%2F-NwLDgR6zAn23Tl-mTff%2FFrame%203.png?alt=media&token=92109220-aa49-41ad-bd2b-48a5fb3cfd18",
    url: "/gallery/ui-concept",
    btnText: "View Details",
    btnRoute: "#",
  },
  {
    id: 2,
    name: "CrudStudio V1",
    desc: "A modern design concept showcased on Dribbble with engaging elements.",
    img: "https://firebasestorage.googleapis.com/v0/b/crudstudio-6fb0f.appspot.com/o/images%2F-NwJwX8Eg0UZy6esrp4I%2FDribbble%20shot%20-%201.png?alt=media&token=2b544c32-4820-4526-a200-b700bac1a04b",
    url: "/gallery/dribbble-showcase",
    btnText: "Explore Now",
    btnRoute: "#",
  },
  {
    id: 3,
    name: "Gym PT Booking App",
    desc: "An innovative app prototype with smooth interactions and animations.",
    img: "https://firebasestorage.googleapis.com/v0/b/crudstudio-6fb0f.appspot.com/o/images%2F-NwJpQjNZB9iRvbz2Mtz%2Fthumbnail?alt=media&token=aee4500e-f6ce-41c9-9f2d-32b341ade8e3",
    url: "/gallery/app-prototype",
    btnText: "Check it Out",
    btnRoute: "#",
  },
  {
    id: 4,
    name: "XYDD Clothing",
    desc: "A cutting-edge 3D UI design concept pushing the boundaries of creativity.",
    img: "https://cdn.dribbble.com/userupload/16588317/file/original-557d802b4e65b7ff516e3d31c8ecbc34.png?format=webp&resize=640x480&vertical=center",
    url: "/gallery/3d-ui",
    btnText: "View Project",
    btnRoute: "#",
  },

  {
    id: 7,
    name: "Skye Social Media",
    desc: "A beautifully designed e-commerce UI for seamless shopping experiences.",
    img: "https://firebasestorage.googleapis.com/v0/b/crudstudio-6fb0f.appspot.com/o/images%2F-NwKWnWn_ddKMuSW3OM9%2FFrame%203.png?alt=media&token=af3fa1fa-6d4d-4fcf-9942-c7bfebae7831",
    url: "/gallery/ecommerce-ui",
    btnText: "View UI Kit",
    btnRoute: "#",
  },
  {
    id: 8,
    name: "Vegitech Innovative",
    desc: "A clean and modern UI design with minimalistic aesthetics.",
    img: "https://cdn.dribbble.com/userupload/16588231/file/original-e2e6f0741e5bdd6d476a82f66f031493.png?format=webp&resize=640x480&vertical=center",
    url: "/gallery/minimalistic-design",
    btnText: "See Details",
    btnRoute: "#",
  },
  {
    id: 9,
    name: "WizardDigitek Custom Ecomm",
    desc: "A modern and user-friendly dashboard interface with powerful features.",
    img: "https://firebasestorage.googleapis.com/v0/b/crudstudio-6fb0f.appspot.com/o/images%2F-NwJYP1hXcrePoubpCfI%2Fthumbnail?alt=media&token=fefcf140-151a-4d11-a2d5-f2ff78399478",
    url: "/gallery/dashboard-ui",
    btnText: "View Dashboard",
    btnRoute: "#",
  },
  {
    id: 10,
    name: "XYSD Clothing Web",
    desc: "A visually appealing portfolio design to showcase creative work.",
    img: "https://cdn.dribbble.com/userupload/16588308/file/original-040022daf600356ccb0bc767398b6cbe.png?format=webp&resize=640x480&vertical=center",
    url: "/gallery/portfolio-design",
    btnText: "Explore Portfolio",
    btnRoute: "#",
  },
  {
    id: 11,
    name: "GoatTapper MemeCoin",
    desc: "A high-converting landing page design optimized for engagement.",
    img: "https://cdn.dribbble.com/userupload/24462903/file/original-73421f2186304e62be0bf1fd29aab64d.jpeg?resize=1504x856&vertical=center",
    url: "/gallery/landing-page",
    btnText: "Visit Page",
    btnRoute: "#",
  },
];

export default imageGallery;
